export interface LocationPreset {
  id: string;
  category: string;
  label: string;
  description: string;
}

export const LOCATION_PRESETS: LocationPreset[] = [

  // ── URBAN / CITY ────────────────────────────────────────────────────────────
  { id: 'nyc-rooftop',       category: 'Urban',        label: 'Manhattan Rooftop',         description: 'Rain-slicked Manhattan rooftop at blue hour, the lit city grid stretching endlessly below, puddles reflecting neon and skyscraper glass.' },
  { id: 'paris-alley',       category: 'Urban',        label: 'Parisian Alley',             description: 'Narrow Haussmann-era Parisian alley at dusk, warm amber café light spilling from arched doorways onto cobblestone, cigarette smoke drifting through the glow.' },
  { id: 'tokyo-crossing',    category: 'Urban',        label: 'Tokyo Crossing',             description: 'Shibuya pedestrian crossing at midnight, neon signage blurred overhead, wet pavement mirroring the chaos of light and city movement.' },
  { id: 'brooklyn-bridge',   category: 'Urban',        label: 'Brooklyn Bridge Walk',       description: 'Brooklyn Bridge walkway at golden hour, steel suspension cables catching amber light, the East River glinting far below.' },
  { id: 'hk-walkway',        category: 'Urban',        label: 'Hong Kong Elevated Walk',    description: 'Hong Kong elevated pedestrian walkway at night, layers of glowing neon signage receding overhead, wet tile underfoot.' },
  { id: 'la-freeway',        category: 'Urban',        label: 'LA Freeway Overpass',        description: 'Los Angeles freeway overpass at sunset, pink and amber smog gradient painting the sky, tail lights streaming below like rivers of fire.' },
  { id: 'dubai-deck',        category: 'Urban',        label: 'Dubai Observation Deck',     description: 'Dubai luxury tower observation deck at twilight, mirrored skyscrapers receding to infinity, desert horizon glowing violet at the edge.' },
  { id: 'london-mews',       category: 'Urban',        label: 'London Mews at Dawn',        description: 'Quiet London stone cobblestone mews at dawn, blue-grey morning mist softening the Georgian brick, window boxes pale in the early light.' },
  { id: 'milan-via',         category: 'Urban',        label: 'Milan Fashion District',     description: 'Via Montenapoleone at dusk, luxury boutique windows glowing warm gold, the Italian stone pavement reflecting the last of the sunset.' },
  { id: 'nyc-subway',        category: 'Urban',        label: 'NYC Subway Platform',        description: 'New York City 1920s subway platform, ornate mosaic tile walls, harsh fluorescent wash casting hard shadows, the distant rumble of an approaching train.' },
  { id: 'chicago-river',     category: 'Urban',        label: 'Chicago Riverwalk',          description: 'Chicago Riverwalk at dusk, glass towers reflected in the dark river below, string lights along the promenade beginning to flicker on.' },
  { id: 'berlin-brutalist',  category: 'Urban',        label: 'Berlin Brutalist Courtyard', description: 'East Berlin brutalist concrete courtyard at noon, raw poured concrete casting hard geometric shadows, wildflowers pushing through the cracked pavement.' },
  { id: 'barcelona-gothic',  category: 'Urban',        label: 'Barcelona Gothic Quarter',   description: 'Barcelona Gothic Quarter narrow lane at late afternoon, warm medieval stone walls channeling a shaft of golden light, wrought iron lanterns above.' },
  { id: 'seoul-arcade',      category: 'Urban',        label: 'Seoul Luxury Arcade',        description: 'Seoul high-end shopping arcade interior, floor-to-ceiling polished marble, soaring glass atrium diffusing cool white light from above.' },
  { id: 'sydney-harbour',    category: 'Urban',        label: 'Sydney Harbour View',        description: 'Sydney Harbour lookout at sunset, the Opera House silhouetted in coral and violet, sailboats cutting slow lines across the glowing water.' },
  { id: 'dumbo-arch',        category: 'Urban',        label: 'DUMBO Bridge Arch',          description: 'DUMBO Brooklyn cobblestone street, the Manhattan Bridge stone arch perfectly framing a shaft of golden afternoon light, the city beyond.' },
  { id: 'rome-piazza',       category: 'Urban',        label: 'Roman Piazza at Dusk',       description: 'Ancient Roman piazza at blue hour, travertine fountains lit from below, tourists dissolved into shadow, the cobblestones catching warm amber lamplight.' },
  { id: 'miami-deco',        category: 'Urban',        label: 'Miami Art Deco Strip',       description: 'Miami South Beach Art Deco strip at magic hour, pastel facades bathed in coral light, palm silhouettes, ocean breeze bending the fronds.' },
  { id: 'amsterdam-canal',   category: 'Urban',        label: 'Amsterdam Canal Bridge',     description: 'Amsterdam canal bridge at dusk, narrow gabled townhouses reflected perfectly in still water, bicycle lights beginning to glow along the stone embankment.' },
  { id: 'singapore-marina',  category: 'Urban',        label: 'Singapore Marina Bay',       description: 'Singapore Marina Bay waterfront at night, the triple-towered hotel lit spectacularly, laser reflections rippling across the dark bay water.' },

  // ── NATURE ──────────────────────────────────────────────────────────────────
  { id: 'sahara-dune',       category: 'Nature',       label: 'Saharan Dune Crest',         description: 'Saharan desert dune crest at golden hour, wind-sculpted ridgelines stretching to the horizon, warm amber light raking across the sand in long shadows.' },
  { id: 'iceland-beach',     category: 'Nature',       label: 'Icelandic Black Beach',       description: 'Icelandic black volcanic sand beach at low tide, dramatic basalt column formations, steel-grey sky, white surf collapsing against dark stone.' },
  { id: 'tuscany-dawn',      category: 'Nature',       label: 'Tuscany at Dawn',             description: 'Tuscan hillside at dawn, rolling green fields and terracotta-roofed farmhouses dissolving into morning mist, lone cypress trees as dark vertical punctuation.' },
  { id: 'amalfi-path',       category: 'Nature',       label: 'Amalfi Cliff Path',           description: 'Amalfi coast cliff path at midday, turquoise Mediterranean sea far below, bougainvillea cascading over sun-bleached stone walls, blinding white light.' },
  { id: 'scotland-moor',     category: 'Nature',       label: 'Scottish Highland Moorland',  description: 'Scottish highland moorland at dusk, infinite purple heather under a brooding pewter sky, storm light illuminating the distant ben.' },
  { id: 'kyoto-bamboo',      category: 'Nature',       label: 'Kyoto Bamboo Grove',          description: 'Kyoto Arashiyama bamboo grove at dawn, pale green light filtering through the vertical stalks, the path ahead curving into cool silence.' },
  { id: 'maldives-deck',     category: 'Nature',       label: 'Maldivian Overwater Deck',   description: 'Maldivian overwater bungalow deck, translucent turquoise lagoon beneath, infinite blue horizon, the water so clear the coral is visible below.' },
  { id: 'morocco-oasis',     category: 'Nature',       label: 'Moroccan Palm Oasis',         description: 'Saharan palm oasis at sunset, warm terracotta sand, long shadows from date palms, a single still pool reflecting the deepening amber sky.' },
  { id: 'montana-prairie',   category: 'Nature',       label: 'Montana Big Sky Prairie',     description: 'Montana open prairie under a monumental big sky, golden grass bending in the wind, a dramatic anvil cloud building at the distant horizon.' },
  { id: 'japan-blossom',     category: 'Nature',       label: 'Cherry Blossom Garden',       description: 'Japanese cherry blossom garden at peak bloom, pale pink petals drifting on the still air, a stone lantern at the edge of a dark reflecting pond.' },
  { id: 'norway-fjord',      category: 'Nature',       label: 'Norwegian Fjord',             description: 'Norwegian fjord shoreline at midnight sun, black water mirroring the lit sky, sheer cliff walls rising to impossible height on either side.' },
  { id: 'swiss-alpine',      category: 'Nature',       label: 'Swiss Alpine Above Clouds',   description: 'Swiss alpine meadow above the cloud line, wildflowers at feet, the cloud sea below glowing white, jagged snow peaks emerging into blue.' },
  { id: 'santorini-edge',    category: 'Nature',       label: 'Santorini Caldera Edge',      description: 'Santorini caldera edge at sunset, whitewashed cubic walls turning molten gold, the volcanic sea below in deep purple shadow, church domes glowing blue.' },
  { id: 'bali-terrace',      category: 'Nature',       label: 'Bali Rice Terraces',          description: 'Balinese rice terrace at dawn, stepped emerald-green paddies descending into the valley, morning mist rising between the levels, a lone farmer moving below.' },
  { id: 'capetown-table',    category: 'Nature',       label: 'Cape Town Table Mountain',    description: 'Cape Town Table Mountain plateau, fynbos heath stretching to the edge, the Atlantic Ocean sprawling below, Lion\'s Head peak lit in afternoon warmth.' },

  // ── LUXURY INTERIORS ────────────────────────────────────────────────────────
  { id: 'paris-salon',       category: 'Interior',     label: 'Parisian Grand Salon',        description: 'Palatial Parisian salon with gilded mirrors doubling the light of crystal chandeliers, silk wallcoverings, Aubusson rug, afternoon sun pouring through tall casements.' },
  { id: 'villa-pool',        category: 'Interior',     label: 'Modernist Villa Pool',         description: 'Modernist cliff-edge villa infinity pool at dusk, the pool\'s blue tile merging visually with the dark ocean below, warm interior light spilling from glass walls behind.' },
  { id: 'venice-palazzo',    category: 'Interior',     label: 'Venetian Palazzo Hall',       description: 'Venetian palazzo marble entrance hall, afternoon light shafts cutting through frescoed ceilings, the sound of the Grand Canal faint through tall arched windows.' },
  { id: 'cph-studio',        category: 'Interior',     label: 'Copenhagen Design Studio',    description: 'Copenhagen design studio with warm blonde oak floors, northern diffused winter light flooding through floor-to-ceiling windows, a single potted olive tree in the corner.' },
  { id: 'nyc-penthouse',     category: 'Interior',     label: 'NYC Penthouse at Dusk',       description: 'New York penthouse living room with floor-to-ceiling glass on three sides, the Manhattan skyline shifting from gold to violet outside as dusk falls.' },
  { id: 'milan-courtyard',   category: 'Interior',     label: 'Milanese Fashion Courtyard',  description: 'Milanese fashion house inner courtyard, terracotta walls overgrown with climbing ivy, soft afternoon light pooling on the ancient stone floor.' },
  { id: 'london-club',       category: 'Interior',     label: 'London Private Members Club', description: 'Old London private members club, dark walnut paneling, art deco brass lamps casting amber circles, old leather armchairs, the smell of library and whisky.' },
  { id: 'spa-concrete',      category: 'Interior',     label: 'Brutalist Spa Interior',      description: 'Luxury brutalist spa, raw concrete and black slate walls, mineral pool steaming at the center, a single candle\'s warmth reflected in the dark water.' },
  { id: 'tokyo-tearoom',     category: 'Interior',     label: 'Tokyo Minimalist Tea Room',   description: 'Traditional Tokyo tea room, shoji paper screens filtering translucent morning light, a raked gravel garden visible through the open shoji wall, absolute silence.' },
  { id: 'bh-pool-house',     category: 'Interior',     label: 'Beverly Hills Pool House',    description: 'Beverly Hills pool house, white linen curtains drifting in the afternoon breeze, brilliant blue pool reflecting shifting light patterns on the ceiling above.' },
  { id: 'marrakech-riad',    category: 'Interior',     label: 'Marrakech Riad Courtyard',   description: 'Marrakech riad central courtyard, intricate zellige tile floor, orange tree at center, filtered afternoon light through a carved stucco oculus overhead.' },
  { id: 'atelier-studio',    category: 'Interior',     label: 'Parisian Couture Atelier',    description: 'Parisian haute couture atelier, vintage dress forms lined up, floor-length windows with dusty golden afternoon light, bolts of fabric and scattered sketches.' },
  { id: 'private-library',   category: 'Interior',     label: 'Private Library Evening',     description: 'Grand private library, floor-to-ceiling leather-bound books, a green-shaded brass lamp casting warm pools of light, evening darkness pressing at the tall windows.' },
  { id: 'swiss-chalet',      category: 'Interior',     label: 'Swiss Chalet Interior',       description: 'Swiss alpine chalet interior, exposed hand-hewn timber beams, fireplace glow casting amber warmth, fresh snowfall visible through the small-paned window outside.' },
  { id: 'opera-staircase',   category: 'Interior',     label: 'Opera House Grand Stair',     description: 'Grand opera house staircase before curtain, sweeping marble steps, gilt railing, red velvet and gold leaf catching chandelier light, crowd dissolving into background.' },

  // ── INDUSTRIAL / RAW ────────────────────────────────────────────────────────
  { id: 'detroit-factory',   category: 'Industrial',   label: 'Abandoned Detroit Factory',  description: 'Abandoned Detroit automobile factory, broken skylights admitting dramatic shafts of dusty light, wildflowers colonising the cracked concrete floor.' },
  { id: 'london-warehouse',  category: 'Industrial',   label: 'East London Warehouse',      description: 'East London converted warehouse, exposed Victorian brick arches, industrial pendant lamps, raw pine floors worn smooth, the smell of old timber and cold air.' },
  { id: 'shanghai-art',      category: 'Industrial',   label: 'Shanghai Art District',      description: 'Shanghai M50 converted mill art district, raw concrete columns casting hard shadows across unfinished gallery floors, skylights overhead flooding the space with grey northern light.' },
  { id: 'berlin-neon',       category: 'Industrial',   label: 'Berlin Underground Club',    description: 'Berlin underground corridor, exposed brick, red neon tubing along the ceiling casting a brutal crimson wash over everything below.' },
  { id: 'wynwood-walls',     category: 'Industrial',   label: 'Miami Wynwood Murals',       description: 'Miami Wynwood street, floor-to-ceiling painted murals in every direction, blinding afternoon tropical light, chain-link fence shadows across the art.' },
  { id: 'melbourne-lane',    category: 'Industrial',   label: 'Melbourne Laneway',           description: 'Melbourne inner-city laneway, walls layered in peeling street art, fairy lights strung between fire escapes, warm café glow from a doorway, evening settling in.' },
  { id: 'navy-dock',         category: 'Industrial',   label: 'Brooklyn Navy Yard',          description: 'Brooklyn Navy Yard waterfront at dawn, rusted dock pilings, industrial cranes in silhouette, the East River steel-grey, tugboat trails across the flat water.' },
  { id: 'fashion-backstage', category: 'Industrial',   label: 'Fashion Week Backstage',      description: 'Fashion week backstage, white tarp walls, steel clothing racks packed with garments, raw fluorescent tube light, models and stylists in purposeful motion.' },

  // ── GLOBAL / EDITORIAL ──────────────────────────────────────────────────────
  { id: 'capri-cliff',       category: 'Global',       label: 'Capri Rocky Cliff Path',     description: 'Capri limestone cliff path at midday, blinding Mediterranean sun, deep blue water far below framed between white rock faces, wild rosemary in the air.' },
  { id: 'rio-sunset',        category: 'Global',       label: 'Rio de Janeiro Sunset',       description: 'Rio Ipanema beachfront at golden hour, Dois Irmãos twin peaks warm and massive in the background, warm sand, carioca life in the foreground.' },
  { id: 'lagos-waterfront',  category: 'Global',       label: 'Lagos Victoria Island',      description: 'Lagos Victoria Island waterfront terrace at dusk, the modern skyline of the city emerging in the warm haze, Bight of Benin shimmering below.' },
  { id: 'accra-beach',       category: 'Global',       label: 'Accra Golden Hour Beach',     description: 'Accra beachfront at golden hour, traditional wooden fishing pirogues drawn up on the warm sand, Harmattan haze diffusing the intense West African sunset.' },
  { id: 'istanbul-bridge',   category: 'Global',       label: 'Istanbul Galata Bridge',      description: 'Istanbul Galata Bridge at dusk, the Bosphorus catching the last of the sun, the Sultanahmet skyline silhouetted against a deep violet and amber sky.' },
  { id: 'havana-facade',     category: 'Global',       label: 'Havana Pastel Facade',        description: 'Havana crumbling pastel-yellow colonial facade, vintage 1957 Cadillac parked below, afternoon shade carving hard lines across the peeling stucco.' },
  { id: 'buenos-aires',      category: 'Global',       label: 'Buenos Aires La Boca',        description: 'Buenos Aires La Boca colourful corrugated-iron street, saturated paint colours in theatrical afternoon light, tango music drifting from a doorway.' },
  { id: 'mexico-zocalo',     category: 'Global',       label: 'Mexico City Zócalo',          description: 'Mexico City Zócalo plaza at dusk, the baroque metropolitan cathedral lit in deep amber, the vast stone square emptying into blue twilight shadow.' },
  { id: 'mumbai-drive',      category: 'Global',       label: 'Mumbai Marine Drive',         description: 'Mumbai Marine Drive at blue hour, monsoon clouds building offshore, the necklace of streetlights curving along the wet promenade, the Arabian Sea restless below.' },
  { id: 'athens-rooftop',    category: 'Global',       label: 'Athens Acropolis Rooftop',    description: 'Athens rooftop restaurant at night, the Parthenon lit spectacularly in warm amber on its hill above, the ancient marble glowing against a deep blue Mediterranean sky.' },
  { id: 'nairobi-rooftop',   category: 'Global',       label: 'Nairobi Rooftop at Dusk',    description: 'Nairobi rooftop terrace at dusk, acacia tree silhouettes breaking the horizon beyond the city edge, the sky banding through coral, amber and purple.' },
  { id: 'cairo-bazaar',      category: 'Global',       label: 'Cairo Bazaar Shaft of Light', description: 'Khan el-Khalili bazaar in Cairo, a dramatic shaft of afternoon light piercing through the latticed roof onto coloured spice sacks and hammered copper below.' },
  { id: 'marrakech-souq',    category: 'Global',       label: 'Marrakech Souk Alley',        description: 'Marrakech medina souk alley, overhead woven shade cloth casting warm patterned shadow, merchant lanterns glowing amber in the filtered afternoon heat.' },

  // ── CONCEPTUAL / ATMOSPHERIC ────────────────────────────────────────────────
  { id: 'salt-flat',         category: 'Conceptual',   label: 'Salt Flat Mirror',            description: 'Bolivian salt flat at sunset, a perfect mirror of water creating an infinite reflection of the coral and violet gradient sky, the horizon indistinguishable.' },
  { id: 'mountain-lake',     category: 'Conceptual',   label: 'Mountain Lake at Dawn',       description: 'High altitude mountain lake at pre-dawn, absolute stillness, granite peaks reflected perfectly in the black water, the first pale blue light just appearing.' },
  { id: 'glass-bridge',      category: 'Conceptual',   label: 'Glass Bridge Over Fog',       description: 'Glass and steel pedestrian bridge suspended over a fog-filled valley, the forest below invisible, only the bridge structure and the pale morning sky visible.' },
  { id: 'yacht-deck',        category: 'Conceptual',   label: 'Luxury Yacht Open Ocean',    description: 'Private superyacht main deck at sunset, nothing but open Atlantic in every direction, champagne light, sea spray drifting in the warm salt air.' },
  { id: 'private-jet',       category: 'Conceptual',   label: 'Private Jet at Altitude',     description: 'Private jet interior at 38,000 feet, the oval window showing a vast cloudscape lit gold below a dark blue stratosphere, absolute silence.' },
  { id: 'greenhouse-roof',   category: 'Conceptual',   label: 'Rooftop Greenhouse',          description: 'Urban rooftop greenhouse, tropical plants pressing against the glass ceiling, diffused overcast sky above, condensation on the glass, warm and humid inside.' },
  { id: 'highway-dawn',      category: 'Conceptual',   label: 'Empty Highway at Dawn',       description: 'Empty desert highway at dawn, heat shimmer already rising from the asphalt, the road vanishing to a point at the horizon, vast silence on all sides.' },
  { id: 'midnight-forest',   category: 'Conceptual',   label: 'Midnight Forest Clearing',   description: 'Forest clearing at midnight, silver-blue moonlight filtering through the canopy, a perfectly still dark pool at the center catching the sky\'s reflection.' },
  { id: 'helipad-night',     category: 'Conceptual',   label: 'Rooftop Helipad at Night',   description: 'Tower helipad at night, landing lights forming a cross in the dark, the city grid a luminous carpet stretching to the horizon below, the sky absolute black.' },
  { id: 'amphitheatre',      category: 'Conceptual',   label: 'Ancient Amphitheatre Dusk',  description: 'Ancient stone Greek amphitheatre at dusk, honey-warm light raking the carved tiers, wildflowers growing from cracks in the marble, the sea beyond going violet.' },
  { id: 'museum-afterhours', category: 'Conceptual',   label: 'Museum After Hours',          description: 'Natural history museum after closing, dioramas glowing in the surrounding dark, display cases lit from within, footsteps echoing on the marble floor.' },
  { id: 'auction-house',     category: 'Conceptual',   label: 'Auction House Gallery',       description: 'London auction house gallery, masterworks spot-lit dramatically from above, soaring white ceiling, hushed atmosphere, paddle in every white-gloved hand.' },
  { id: 'greenhouse-nursery',category: 'Conceptual',   label: 'Tropical Greenhouse Nursery',description: 'Botanical garden greenhouse, tropical palm fronds and monstera leaves pressing from all sides, diffused glass-filtered light, thick warm humidity.' },
  { id: 'night-market',      category: 'Conceptual',   label: 'Southeast Asia Night Market', description: 'Southeast Asian night market, paper lanterns casting warm amber light over food stalls, smoke from a grill drifting through the humid evening air.' },
  { id: 'train-window',      category: 'Conceptual',   label: 'High-Speed Train, Europe',   description: 'First-class high-speed train, European countryside blurring past the wide window, amber farmland under a dramatic sky, the seat bathed in passing light and shadow.' },

  // ── SEASONAL / WEATHER ──────────────────────────────────────────────────────
  { id: 'ny-snowfall',       category: 'Seasonal',     label: 'New York First Snowfall',    description: 'New York City Central Park in the first snowfall of the year, paths silenced under white, lamp-posts haloed, the skyline beyond the trees grey and soft.' },
  { id: 'london-fog',        category: 'Seasonal',     label: 'London Fog on the Thames',   description: 'London Thames Embankment at dawn, thick white fog dissolving the Victorian lamp-posts into pale silhouettes, the river invisible below, silence everywhere.' },
  { id: 'monsoon-glass',     category: 'Seasonal',     label: 'Monsoon Rain on Glass',       description: 'Tropical monsoon rain hammering a floor-to-ceiling glass wall, city lights streaking into vertical lines through the water, the room inside warm and dry.' },
  { id: 'dust-storm',        category: 'Seasonal',     label: 'Golden Dust Storm Edge',      description: 'The edge of a Saharan dust storm at sunset, a wall of warm amber haze filling half the sky, the air thick and golden, the horizon dissolving.' },
  { id: 'ice-hotel',         category: 'Seasonal',     label: 'Ice Hotel Corridor',          description: 'Lapland ice hotel corridor, the walls translucent blue carved ice, a single chandelier of frozen crystals hanging above, breath visible in the -7° air.' },
  { id: 'autumn-cathedral',  category: 'Seasonal',     label: 'Autumn Forest Cathedral',     description: 'Appalachian forest in peak autumn, the canopy a cathedral of crimson, amber and deep orange, leaf carpet on the path, afternoon sun angled low and golden.' },
  { id: 'aurora',            category: 'Seasonal',     label: 'Nordic Aurora Borealis',      description: 'Finnish Lapland frozen lake at midnight, aurora borealis pulsing green and violet overhead, the ice stretching flat and dark, tree silhouettes at the shore.' },
  { id: 'sunrise-storm',     category: 'Seasonal',     label: 'Sunrise After Storm',         description: 'Ocean horizon just after a storm, a dramatic break in the clouds admitting a shaft of god-rays onto the dark heaving water, a faint rainbow at the edge.' },
  { id: 'cherry-wind',       category: 'Seasonal',     label: 'Cherry Blossom in the Wind', description: 'Japanese garden path in a gust of wind, pale pink cherry blossom petals filling the air like warm snow, stone lanterns and a dark pond at the edge.' },
  { id: 'sandstorm-fortress',category: 'Seasonal',     label: 'Desert Fortress Sandstorm',  description: 'Ancient desert fortress, a wall of amber sandstorm building on the horizon, the air already thick and warm and golden, the dunes ahead disappearing.' },
];

export const LOCATION_CATEGORIES = [
  'Urban',
  'Nature',
  'Interior',
  'Industrial',
  'Global',
  'Conceptual',
  'Seasonal',
] as const;
