/**
 * src/lib/photographyPresets.ts — Photography preset catalog
 *
 * Extracted from PersonaCarousel.tsx to satisfy react-refresh/only-export-components
 * (a file should export either components or constants, not both).
 */

export interface PhotographyPreset {
  id: string;
  name: string;
  vibe: string;       // One-line description in plain language
  tag: string;        // Short mood tag
  lighting: string;
  camera: string;
  bg: string;
  image: string;
}

export const PHOTOGRAPHY_PRESETS: PhotographyPreset[] = [
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    vibe: 'Warm side light — glowing, sun-kissed skin',
    tag: 'Warm & Radiant',
    lighting: 'Sunset Side Glow',
    camera: 'Soft Background (85mm)',
    bg: 'studio-grey',
    image: '/assets/master_hair.png',
  },
  {
    id: 'clean-studio',
    name: 'Clean Studio',
    vibe: 'Bright even light — crisp, professional, nothing to hide',
    tag: 'Clear & Sharp',
    lighting: 'Clean & Even',
    camera: 'Natural Eye (50mm)',
    bg: 'studio-grey',
    image: '/assets/master_nails.png',
  },
  {
    id: 'dark-dramatic',
    name: 'Dark & Dramatic',
    vibe: 'Deep shadows, black background — bold and powerful',
    tag: 'High Contrast',
    lighting: 'Deep Shadow',
    camera: 'Soft Background (85mm)',
    bg: 'pitch-black',
    image: '/assets/master_clothing_noir.png',
  },
  {
    id: 'soft-natural',
    name: 'Soft & Natural',
    vibe: 'Gentle light like a window — effortless and real',
    tag: 'Effortless',
    lighting: 'Soft Natural',
    camera: 'Natural Eye (50mm)',
    bg: 'studio-grey',
    image: '/assets/master_hair.png',
  },
  {
    id: 'bold-beauty',
    name: 'Bold Beauty',
    vibe: 'Overhead glam light — every detail pops on white',
    tag: 'Magazine Glam',
    lighting: 'Beauty Overhead',
    camera: 'Soft Background (85mm)',
    bg: 'editorial-white',
    image: '/assets/master_nails.png',
  },
  {
    id: 'hollywood-glam',
    name: 'Hollywood Glam',
    vibe: 'Old Hollywood beauty light against full black — timeless',
    tag: 'Timeless Classic',
    lighting: 'Beauty Overhead',
    camera: 'Soft Background (85mm)',
    bg: 'pitch-black',
    image: '/assets/master_clothing_noir.png',
  },
  {
    id: 'velvet-night',
    name: 'Velvet Night',
    vibe: 'Moody cinema light — dark, rich, and mysterious',
    tag: 'Dark & Moody',
    lighting: 'Moody Cinema',
    camera: 'Fashion Zoom (135mm)',
    bg: 'pitch-black',
    image: '/assets/master_clothing_noir.png',
  },
  {
    id: 'runway-ready',
    name: 'Runway Ready',
    vibe: 'Fashion week energy — sharp, bright, and commanding',
    tag: 'High Fashion',
    lighting: 'Beauty Overhead',
    camera: 'Fashion Zoom (135mm)',
    bg: 'editorial-white',
    image: '/assets/master_hair.png',
  },
  {
    id: 'power-portrait',
    name: 'Power Portrait',
    vibe: 'One strong shadow light — serious, intense, and in control',
    tag: 'Commanding',
    lighting: 'Deep Shadow',
    camera: 'Soft Background (85mm)',
    bg: 'pitch-black',
    image: '/assets/master_clothing_noir.png',
  },
  {
    id: 'luxury-closeup',
    name: 'Luxury Close-Up',
    vibe: 'Macro detail — every texture and thread fully visible',
    tag: 'Ultra Detail',
    lighting: 'Clean & Even',
    camera: 'Ultra Close-Up (Macro)',
    bg: 'studio-grey',
    image: '/assets/master_nails.png',
  },
  {
    id: 'sun-kissed',
    name: 'Sun Kissed',
    vibe: 'Warm golden tone — rich, glowing, full of life',
    tag: 'Warm Glow',
    lighting: 'Sunset Side Glow',
    camera: 'Natural Eye (50mm)',
    bg: 'studio-grey',
    image: '/assets/master_hair.png',
  },
  {
    id: 'pure-white',
    name: 'Pure White',
    vibe: 'Clean white everything — fresh, airy, and bright',
    tag: 'Light & Airy',
    lighting: 'Clean & Even',
    camera: 'Natural Eye (50mm)',
    bg: 'editorial-white',
    image: '/assets/master_nails.png',
  },
  {
    id: 'soft-romance',
    name: 'Soft Romance',
    vibe: 'Dreamy window light on white — delicate and ethereal',
    tag: 'Dreamy',
    lighting: 'Soft Natural',
    camera: 'Soft Background (85mm)',
    bg: 'editorial-white',
    image: '/assets/master_hair.png',
  },
  {
    id: 'street-story',
    name: 'Street Story',
    vibe: 'Wide angle, real-world light — documentary and alive',
    tag: 'Real & Raw',
    lighting: 'Soft Natural',
    camera: 'Street Style (35mm)',
    bg: 'custom-bg',
    image: '/assets/master_clothing_noir.png',
  },
  {
    id: 'chrome-edge',
    name: 'Chrome Edge',
    vibe: 'Dark cinematic mood, fashion zoom — sleek and futuristic',
    tag: 'Modern & Sharp',
    lighting: 'Moody Cinema',
    camera: 'Fashion Zoom (135mm)',
    bg: 'pitch-black',
    image: '/assets/master_clothing_noir.png',
  },
  {
    id: 'editorial-wide',
    name: 'Editorial Wide',
    vibe: 'Full body, full story — wide angle with environment visible',
    tag: 'Full Frame Story',
    lighting: 'Clean & Even',
    camera: 'Editorial Wide (24mm)',
    bg: 'custom-bg',
    image: '/assets/master_hair.png',
  },
  {
    id: 'warm-earth',
    name: 'Warm Earth',
    vibe: 'Sunset warmth, grounded and organic — rich human tones',
    tag: 'Earthy & Organic',
    lighting: 'Sunset Side Glow',
    camera: 'Natural Eye (50mm)',
    bg: 'studio-grey',
    image: '/assets/master_nails.png',
  },
  {
    id: 'candid-charm',
    name: 'Candid Charm',
    vibe: 'Soft light, street lens — relaxed, genuine, no posing',
    tag: 'Genuine & Relaxed',
    lighting: 'Soft Natural',
    camera: 'Street Style (35mm)',
    bg: 'studio-grey',
    image: '/assets/master_hair.png',
  },
  {
    id: 'fierce-bold',
    name: 'Fierce & Bold',
    vibe: 'Compressed zoom, deep shadow — fashion-forward and fearless',
    tag: 'Fearless',
    lighting: 'Deep Shadow',
    camera: 'Fashion Zoom (135mm)',
    bg: 'pitch-black',
    image: '/assets/master_clothing_noir.png',
  },
  {
    id: 'raw-energy',
    name: 'Raw Energy',
    vibe: 'Wide lens, side light — full body, dynamic and in motion',
    tag: 'Dynamic',
    lighting: 'Sunset Side Glow',
    camera: 'Street Style (35mm)',
    bg: 'studio-grey',
    image: '/assets/master_hair.png',
  },
];
